# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'nextcloud'
    
    scrape_interval: 90s
    
    static_configs:
      - targets: ['192.168.31.235:5212']